// <auto-generated />
namespace TodoMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateIndex_Tasks_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateIndex_Tasks_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201211230413417_CreateIndex_Tasks_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
